[package]
name = "tic_tac_toe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clearscreen = "2.0.0"
rand = "0.8.5"

#[env]
#ENABLE_VIRTUAL_TERMINAL_PROCESSING=1

#[profile.dev]
#opt-level = 1